---

- hosts: rails
  remote_user: root
  roles:
    - { role: selinux, tags: selinux }
    - { role: cron, tags: cron }
    - { role: timezone, tags: timezone }
    - { role: ntp, tags: ntp }
    - { role: git, tags: git }

