---

- name: Check timezone
  stat: path=/etc/localtime
  register: timezone

- name: Delete timezone configuration
  file: path=/etc/localtime
        state=absent
  when: timezone.stat.isreg or (timezone.stat.lnk_source != "/usr/share/zoneinfo/Europe/London")

- name: Set timezone
  file: src=/usr/share/zoneinfo/Europe/London
        dest=/etc/localtime
        state=link

